name: barcode_ta
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  barcode_scanner: ^3.2.4
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.2.1
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.5
  google_fonts: ^4.0.4
  mobile_scanner: ^3.2.0
  open_file: ^3.2.1
  path_provider: ^2.0.15
  pdf: ^3.3.0
  permission_handler: ^10.2.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.11
  image_picker: ^0.8.7+5
  
  flutter: 
    sdk: flutter
  flutter_typeahead: ^4.6.1
  dropdown_search: ^5.0.6
  rxdart: ^0.27.7
  intl: ^0.18.1
  numberpicker: ^2.1.2
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo2.png"

dev_dependencies: 
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/splash.png
    - assets/logo/splash3.png
    - assets/logo/poltek.png
    - assets/logo/login.png
    - assets/logo/ellipse1.png
    - assets/logo/ellipse2.png
    - assets/logo/ellipse3.png
    - assets/logo/ellipse4.png
    - assets/icons/image3.png
    - assets/icons/plus.png
    - assets/icons/catalog.png
    - assets/icons/trash.png
    - assets/logo/logo2.png
    
    
  uses-material-design: true

